# update marker: begin {B1B2EA1E-4F42-4C75-B4DB-C41BE62ADABE}
version: 2
updates:
  # update marker:   end {B1B2EA1E-4F42-4C75-B4DB-C41BE62ADABE}
  # update marker: begin {5C7FB3C3-F874-4239-BED0-8F2378227C04}
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - thnetii/organization
  # update marker:   end {5C7FB3C3-F874-4239-BED0-8F2378227C04}
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    reviewers:
      - thnetii/organization
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    reviewers:
      - thnetii/organization
